export interface BaseStockItem {
  name: string;
  unit: string;
  category: string;
  currentStock: number;
  minStock: number;
}

export const defaultStockItems: BaseStockItem[] = [
  { name: "ABACATE", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 9, minStock: 0 },
  { name: "ABACAXI", unit: "PÇ", category: "ALIMENTAÇÃO", currentStock: 14, minStock: 6 },
  { name: "ABOBORA CABOTIA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "ABOBORA MORANGA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "ABOBRINHA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 3 },
  { name: "ACELGA", unit: "MÇ", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 1 },
  { name: "ACHOCOLATADO EM PO (400G)", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 10 },
  { name: "ACHOCOLATADO EM PO MORANGO", unit: "UN", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 2 },
  { name: "ADOÇANTE LIQUIDO", unit: "FR", category: "ALIMENTAÇÃO", currentStock: 3, minStock: 4 },
  { name: "AGRIAO", unit: "MÇ", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "AGUA DE CÔCO", unit: "L", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "ALCAPARRA", unit: "FR", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "ALFACE", unit: "MÇ", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 1 },
  { name: "ALHO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 15, minStock: 5 },
  { name: "ALMEIRAO", unit: "MÇ", category: "ALIMENTAÇÃO", currentStock: 30, minStock: 1 },
  { name: "AMEIXA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "AMENDOIM", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 1 },
  { name: "AMIDO DE MILHO", unit: "CX", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "ARROZ 5KG", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 123, minStock: 120 },
  { name: "ARROZ PACOTE 1KG", unit: "UN", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "ATUM CONSERVA", unit: "UN", category: "ALIMENTAÇÃO", currentStock: 3, minStock: 5 },
  { name: "AVEIA EM FLOCOS", unit: "CX", category: "ALIMENTAÇÃO", currentStock: 1, minStock: 1 },
  { name: "AZEITE EXTRA VIRGEM 500ml", unit: "FR", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "AZEITONA FATIADA 120G", unit: "SACHE", category: "ALIMENTAÇÃO", currentStock: 14, minStock: 0 },
  { name: "AZEITONA PRETA 2,0 KG", unit: "BD", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "AÇUCAR CRISTAL 1KG", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 17, minStock: 0 },
  { name: "AÇUCAR CRISTAL 5KG", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 8, minStock: 50 },
  { name: "BACON", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 12, minStock: 1 },
  { name: "BANANA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 40, minStock: 20 },
  { name: "BATATA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 29, minStock: 5 },
  { name: "BATATA DOCE", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 2 },
  { name: "BOLACHA AGUA E SAL", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 6, minStock: 20 },
  { name: "BOLACHA MAISENA", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 73, minStock: 20 },
  { name: "BOLACHA RECHEADA", unit: "UN", category: "ALIMENTAÇÃO", currentStock: 41, minStock: 0 },
  { name: "BROCOLIS", unit: "PÇ", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 6 },
  { name: "CAFE 500g", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 153, minStock: 40 },
  { name: "CARNE BOVINA (ACEM)", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 0 },
  { name: "CARNE BOVINA (COXAO DURO)", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "CARNE BOVINA (MOÍDA)", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 10 },
  { name: "CEBOLA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 130, minStock: 0 },
  { name: "CENOURA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 3 },
  { name: "COCA COLA", unit: "L", category: "ALIMENTAÇÃO", currentStock: 2, minStock: 0 },
  { name: "COUVE", unit: "MÇ", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 1 },
  { name: "COXA/SOBRECOXA FRANGO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 10 },
  { name: "CREME DE LEITE", unit: "CX", category: "ALIMENTAÇÃO", currentStock: 13, minStock: 5 },
  { name: "DIETA ENTERAL GI CONTROL", unit: "L", category: "ALIMENTAÇÃO", currentStock: 11, minStock: 10 },
  { name: "FARINHA MANDIOCA", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 22, minStock: 0 },
  { name: "FEIJAO CARIOCA 1KG", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 52, minStock: 50 },
  { name: "FEIJAO PRETO 1KG", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 0 },
  { name: "FIGADO BOVINO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "FUBA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 45, minStock: 20 },
  { name: "GELATINA", unit: "CX", category: "ALIMENTAÇÃO", currentStock: 219, minStock: 20 },
  { name: "LARANJA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 40, minStock: 5 },
  { name: "LEITE INTEGRAL", unit: "L", category: "ALIMENTAÇÃO", currentStock: 1646, minStock: 200 },
  { name: "LINGUIÇA TOSCANA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "MACARRAO", unit: "PCT", category: "ALIMENTAÇÃO", currentStock: 216, minStock: 50 },
  { name: "Margarina C/SAL 500g", unit: "PT", category: "ALIMENTAÇÃO", currentStock: 40, minStock: 10 },
  { name: "MELAO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 12, minStock: 5 },
  { name: "MILHO VERDE 170G", unit: "SACHE", category: "ALIMENTAÇÃO", currentStock: 52, minStock: 0 },
  { name: "OVOS (CARTELA C/20)", unit: "CT", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "PEITO DE FRANGO C/OSSO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "PEIXE FILE MERLUZA", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "PERNIL SUÍNO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 10 },
  { name: "PIMENTAO VERDE", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 44, minStock: 2 },
  { name: "REPOLHO", unit: "PÇ", category: "ALIMENTAÇÃO", currentStock: 10, minStock: 6 },
  { name: "SAL REFINADO", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 116, minStock: 15 },
  { name: "SARDINHA", unit: "LT", category: "ALIMENTAÇÃO", currentStock: 17, minStock: 15 },
  { name: "TOMATE", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 0, minStock: 5 },
  { name: "VAGEM", unit: "KG", category: "ALIMENTAÇÃO", currentStock: 16, minStock: 0 },
  { name: "VINAGRE", unit: "L", category: "ALIMENTAÇÃO", currentStock: 44, minStock: 12 }
];
